services:
  - type: web
    name: deepthink-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OLLAMA_API_URL
        value: http://ollama:11434/api/chat
      - key: OLLAMA_HOST
        value: ollama
      - key: OLLAMA_PORT
        value: 11434
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_PERIOD
        value: 60
      - key: MAX_CONNECTIONS
        value: 20
      - key: REQUEST_TIMEOUT
        value: 300
      - key: MAX_REQUEST_SIZE
        value: 10485760
      - key: LOG_LEVEL
        value: INFO

  - type: web
    name: ollama
    env: docker
    dockerfilePath: Dockerfile.ollama
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
      - key: OLLAMA_PORT
        value: 11434 